### ISSUE TITLE
Special character in ssh password for faucet controller

### ISSUE THREAD

**Issue by alshaboti** [CyberReboot/poseidon#472] opened 2018-01-02 17:15 UTC
I got this error when ssh password for faucet controller (controller_pass) contains special characters (?!). 

2018-01-03T05:30:06+00:00 172.17.0.1 plugin[23077]: 2018-01-02 16:30:06,489 - ERROR - UpdateSwitchState:120 - FaucetProxy could not connect to 192.168.2.10 because invalid character in identifier (<unknown>, line 1)

**Comment by cglewis** [comment] 2018-01-02 17:20
can you give an example of reproducible steps?  did you export the password as an environment variable or change it in the config directly? was the variable quoted?

**Comment by alshaboti** [comment] 2018-01-02 17:26
I exported it without quotation, like this:
export controller_pass=wz.kde?1

Should I quote it?

**Comment by cglewis** [comment] 2018-01-02 17:27
for that example, it shouldn't need to be quoted, others like spaces or `#` would need to be. let me look into this and see if I can track it down. thanks for reporting it!

**Comment by cglewis** [comment] 2018-01-03 16:23
I have been unable to reproduce this so far, but I have a few more things to verify.  Any other information you can provide though in your setup/environment/version would be helpful though.

**Comment by alshaboti** [comment] 2018-01-04 22:18
Sorry, 
I try it again with the same password, and it works fine. 
I am not sure what was the problem that time.

**Comment by cglewis** [comment] 2018-01-04 22:42
ok, cool.  Closing - if you can reproduce, feel free to reopen with those details.

**Closed by cglewis** 2018-01-04 22:42 UTC
Labels: bug, FAUCET
