### ISSUE TITLE
[Errno 21] Is a directory: '/etc/faucet/faucet.yaml'

### ISSUE THREAD

**Issue by jaiken06** [CyberReboot/poseidon#650] opened 2018-07-03 10:07 UTC
I have started to receive this error in the Poseidon logs: 

```
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,547 - ERROR - parser:54  - failed to load config
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,547 - ERROR - parser:55  - [Errno 21] Is a directory: '/etc/faucet/faucet.yaml'
```

In full:
```
2018-07-03T10:58:30+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:30,882 - INFO - EndpointWrapper:103 - *******UNKNOWN*********
2018-07-03T10:58:30+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:30,882 - INFO - EndpointWrapper:131 - U:c39e9a4e1d6017f4793ff179c1d499f2c3f05907:UNKNOWN->MIRRORING:{'mac': '70:ee:50:18:34:43', 'ip': '192.168.1.241', 's': '123917682136133', 'p': '1', 'v': 'VLAN100'}
2018-07-03T10:58:30+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:30,888 - INFO - EndpointWrapper:103 - *******MIRRORING*********
2018-07-03T10:58:30+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:30,889 - INFO - EndpointWrapper:135 - None
2018-07-03T10:58:30+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:30,889 - INFO - EndpointWrapper:103 - *******SHUTDOWN*********
2018-07-03T10:58:30+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:30,889 - INFO - EndpointWrapper:135 - None
2018-07-03T10:58:30+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:30,889 - INFO - EndpointWrapper:103 - *******REINVESTIGATING*********
2018-07-03T10:58:30+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:30,889 - INFO - EndpointWrapper:135 - None
2018-07-03T10:58:30+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:30,889 - INFO - EndpointWrapper:144 - ****************
2018-07-03T10:58:30+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:30,889 - INFO - EndpointWrapper:145 - ====STOP
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,547 - ERROR - parser:54  - failed to load config
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,547 - ERROR - parser:55  - [Errno 21] Is a directory: '/etc/faucet/faucet.yaml'
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,547 - INFO - EndpointWrapper:140 - ====START
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,547 - INFO - EndpointWrapper:103 - *******KNOWN*********
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,547 - INFO - EndpointWrapper:135 - None
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,547 - INFO - EndpointWrapper:103 - *******UNKNOWN*********
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,547 - INFO - EndpointWrapper:135 - None
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,548 - INFO - EndpointWrapper:103 - *******MIRRORING*********
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,548 - INFO - EndpointWrapper:131 - M:c39e9a4e1d6017f4793ff179c1d499f2c3f05907:MIRRORING->NONE:{'mac': '70:ee:50:18:34:43', 'ip': '192.168.1.241', 's': '123917682136133', 'p': '1', 'v': 'VLAN100'}
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,563 - INFO - EndpointWrapper:103 - *******SHUTDOWN*********
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,569 - INFO - EndpointWrapper:135 - None
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,569 - INFO - EndpointWrapper:103 - *******REINVESTIGATING*********
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,570 - INFO - EndpointWrapper:135 - None
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,570 - INFO - EndpointWrapper:144 - ****************
2018-07-03T10:58:31+00:00 172.17.0.1 cyberreboot-poseidon-master-HEAD/cf91cc3870f7/plugin[1494]: 2018-07-03 09:58:31,570 - INFO - EndpointWrapper:145 - ====STOP
```

I have determined that it stems from the parser.py and is due to the faucet.yaml being unreadable.  So I went into the Poseidon container to /etc/faucet/faucet.yaml and noticed that the faucet.yaml file was indeed a directory as the error has stated.

Somehow this text file has been changed to a directory.  I went to my controller where faucet is running and checked its file in etc/faucet/faucet.yaml, it too was now a directory.

I changed the faucet.yaml on the controller back to a text file and then rebuilt it and rebuilt Poseidon however again, the faucet.yaml that was copied to Poseidon was a directory instead of a text file.

Any idea why this may be the case?

**Comment by cglewis** [comment] 2018-07-03 14:59
What version of Faucet are you using?  Either way, Poseidon definitely shouldn't be creating a directory in place of files, so that is troublesome.  I'll see if I can track down what could be cause that.  I suspect it's something with the way Docker is mapping the volumes, since Docker will sometimes create it as a directory if it can't find the file it's mapping.  Let me get back to you.

**Comment by cglewis** [comment] 2018-07-03 16:11
I was able to reproduce the `faucet.yaml` file becoming a directory by deleting the file.  If no `/etc/faucet/faucet.yaml` file exists when the container starts, it will create it as a directory, which it shouldn't be doing. I'll work on a fix.

**Comment by cglewis** [comment] 2018-07-03 16:33
@jaiken06 i pushed up a quick fix for this. you'll need to make sure and remove `faucet.yaml` if it's already a directory first and pull down the latest poseidon code.  I was only able to reproduce this behavior if the file was missing when the container started, now if the file is missing will just create it with the correct file type, rather than a directory.  let me know if this resolves the issue, or if there's soemthing else at play here that I haven't been able to reproduce.

**Comment by jaiken06** [comment] 2018-07-04 11:20
Thanks very much,

When trying to delete the faucet.yaml within the Poseidon container with:
`rm -r faucet.yaml`

 It says:

`rm: can't remove 'faucet.yaml': Resource busy`

I have tried this on both the older build and then the newest build of Poseidon.  I tried killing one of the processes within the container so it wouldn't be accessing `faucet.yaml` but it crashed the container.

How can I go about deleting this faucet.yaml? It seems awkward because the container is only up when that file is being accessed right?  Is there a way I can just force remove it?
Thanks

**Comment by cglewis** [comment] 2018-07-04 14:05
The Poseidon container is started with a Docker volume to `faucet.yaml`, meaning it maps the existing file on your host into the container. You wouldn't want to delete the file inside the container. You'll want to remove the container, look at the file on the host - if it's a directory, remove it. Then start Poseidon again.

**Comment by jaiken06** [comment] 2018-07-04 15:30
I am on the latest version and have deleted the directory /etc/faucet.

When I run Poseidon, it recreates it as `/etc/faucet/faucet.yaml/faucet.yaml`, I have tried this a few times just to confirm.

`faucet.yaml` being a directory and then the second `faucet.yaml` being the actual file, this produces the same error `is a directory`

**Comment by cglewis** [comment] 2018-07-04 16:04
That is really strange. What version of Faucet are you using?

**Comment by jaiken06** [comment] 2018-07-05 07:37
Honestly I didn't even think of just manually replacing the file rather than just deleting and letting Poseidon do it.

I have replaced it myself and put in the correct file and it is working and not showing the error, that has been a successful workaround.  I am not sure what was causing this problem.

My faucet is `Faucet 1.8.2`

**Comment by cglewis** [comment] 2018-07-05 14:37
Glad to here this is resolved.  I would also recommend upgrading to at least Faucet 1.8.6 as they recently changed the way they parse their yaml file.

**Closed by cglewis** 2018-07-05 14:37 UTC
Labels: FAUCET, bug
